import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/themeToggleButton";
import Aurora from "@/components/aroura";



const DMSans = DM_Sans({
  weight: "400",
  subsets: ["latin"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMSans.className} antialiased`}
      >
        <div className="absolute top-0 w-screen z-[-1] h-[40vh] backdrop-blur-md">
          <Aurora  colorStops={["#FF3C38", "#FF7F11", "#5B2C6F"]}

          blend={0.5}

          amplitude={1.0}

          speed={0.5} />
        </div>
        <ThemeProvider
          attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          
          <ModeToggle />

          {children}

        </ThemeProvider>
        
      </body>
    </html>
  );
}
